### ISSUE TITLE
Не подключается к серверу

### ISSUE THREAD

**Issue by AnF46** [AnF46/hwPatterns2#1]
# Описание
не подключается к серверу, ни через сам терминал, ни через терминал IDEA. появляется ошибка, что сервер уже в работе -  "Exception in thread "DefaultDispatcher-worker-3" java.net.BindException: Address already in use".
Пробовала вс закрывать программы и снова  открывать, не помогло.

# Шаги воспроизведения
1. настройка проекта в IDEA и GIT - добавлен код, настроен гит игнор.
2. добавлен jar файл в папку проекта, в папку artifacts.
3. настроен yml appveyor.
4. в GIT добавлено исключение, чтобы он отслеживал jar файл.
5. запуск сервера через терминал в IDEA командой "java -jar ./artifacts/app-ibank.jar -P:profile=test" .
6. попытка запуска через терминала на ноутбук, той же командой - "java -jar ./artifacts/app-ibank.jar -P:profile=test" .

* Ожидаемый результат - подключение сервера, открытие страницы в браузере.
* Фактический результат - ошибка - сервер уже в работе; страница браузера не открывается ошибка - server error

# Скриншот
![Снимок экрана 2024-11-23 в 23 54 45](https://github.com/user-attachments/assets/609d4e22-8b65-4aff-9a91-7737a2aa390f)

# Логи сборки

<details>
<summery>error log</summary>

```txt
anf@MacBook-Air-AnF hwPatterns2 % java -jar ./artifacts/app-ibank.jar -P:profile=test
2024-11-24 10:11:37.299 [main] TRACE Application - {
    # application.conf @ jar:file:/Users/anf/IdeaProjects/hwPatterns2/artifacts/app-ibank.jar!/application.conf: 6
    "application" : {
        # application.conf @ jar:file:/Users/anf/IdeaProjects/hwPatterns2/artifacts/app-ibank.jar!/application.conf: 7
        "modules" : [
            # application.conf @ jar:file:/Users/anf/IdeaProjects/hwPatterns2/artifacts/app-ibank.jar!/application.conf: 7
            "ru.netology.aqa.ApplicationKt.module"
        ]
    },
    # application.conf @ jar:file:/Users/anf/IdeaProjects/hwPatterns2/artifacts/app-ibank.jar!/application.conf: 2
    "deployment" : {
        # application.conf @ jar:file:/Users/anf/IdeaProjects/hwPatterns2/artifacts/app-ibank.jar!/application.conf: 3
        "port" : 9999
    },
    # Content hidden
    "security" : "***"
}

2024-11-24 10:11:37.341 [DefaultDispatcher-worker-1] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2024-11-24 10:11:37.553 [DefaultDispatcher-worker-1] INFO  Application - Responding at http://0.0.0.0:9999
Exception in thread "DefaultDispatcher-worker-3" java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:73)
        at io.ktor.network.sockets.TcpSocketBuilder.bind(Builders.kt:125)
        at io.ktor.network.sockets.TcpSocketBuilder.bind$default(Builders.kt:116)
        at io.ktor.server.cio.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:92)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

</details>

#Окружение
* **Операционная система: mac OS Sequoia 15.1
* **IDE: IntelliJ IDEA 2023.1.1 (Community Edition)
* **openjdk version "11.0.19" 2023-04-18 LTS
* **OpenJDK Runtime Environment Corretto-11.0.19.7.1 (build 11.0.19+7-LTS)
* **OpenJDK 64-Bit Server VM Corretto-11.0.19.7.1 (build 11.0.19+7-LTS, mixed mode)

**Comment by andrew-pahomov** [comment]
5 и 6 шаги работать вместе точно не будут. Вы не можете запустить одновременно два учебных приложения. Один из шагов надо убрать.                 

Остановите все ранее запущенные учебные приложения и выполните запуск снова. Логи прошу показывать на скринах. Рекомендую перезагрузить машину.

**Comment by AnF46** [comment]
@andrew-pahomov 
5-6 я имела ввиду, что пробовала и тот и другой вариант запуска)
пробовала их по отдельности. надо было мне детальнее расписать шаги(

**Перезагрузка и даже установка обновления macOS помогли. через терминал IDEA запустился, страница в браузере открылась. Благодарю за помощь!**

подскажите, а как остановить в терминале IDEA? в обычном терминале использую клавишу command + Q, тогда процесс останавливается и можно вводить новые команды. но такая команда в терминале IDEA закрывает приложение IDEA, да процесс останавливается, но думаю, что это не совсем корректно. Подскажите, пожалуйста, есть ли другая команда для остановки?
